name: ci

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NOMAD_ADDR: http://feziv.com:4646

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: build and deploy master image to ghcr.io
        env:
          GITHUB_PACKAGE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.actor }}
          GITHUB_REF: ${{ github.ref }}
        run: |
          ref="$(echo ${GITHUB_REF} | cut -d'/' -f3)"
          echo GITHUB_REF - $ref
          echo ${GITHUB_PACKAGE_TOKEN} | docker login ghcr.io -u ${USERNAME} --password-stdin
          docker buildx build --push \
            --build-arg GIT_BRANCH=${ref} \
            --platform linux/amd64 \
            -t ghcr.io/${USERNAME}/rp:${ref} .

      - name: Deploy with Nomad
        uses: docker://hashicorp/levant:latest
        with:
          args: levant deploy web-service.hcl