name: ci

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NOMAD_ADDR: http://feziv.com:4646

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          path: public/

      - name: Deploy with Nomad
        uses: docker://hashicorp/levant:latest
        with:
          args: levant deploy  web-service.hcl