name: ci

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NOMAD_ADDR: feziv.com:4646

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Deploy with Nomad
        uses: docker://hashicorp/levant:latest

      - name: Run levant
      - run: levant deploy web-service.hcl
